
package STUB_Proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://banqueservice.icodi.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @return
     *     returns java.util.List<STUB_Proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listComptes", targetNamespace = "http://banqueservice.icodi.com/", className = "STUB_Proxy.ListComptes")
    @ResponseWrapper(localName = "listComptesResponse", targetNamespace = "http://banqueservice.icodi.com/", className = "STUB_Proxy.ListComptesResponse")
    @Action(input = "http://banqueservice.icodi.com/BanqueService/listComptesRequest", output = "http://banqueservice.icodi.com/BanqueService/listComptesResponse")
    public List<Compte> listComptes();

    /**
     * 
     * @param code
     * @return
     *     returns STUB_Proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://banqueservice.icodi.com/", className = "STUB_Proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://banqueservice.icodi.com/", className = "STUB_Proxy.GetCompteResponse")
    @Action(input = "http://banqueservice.icodi.com/BanqueService/getCompteRequest", output = "http://banqueservice.icodi.com/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroToMAD")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToMAD", targetNamespace = "http://banqueservice.icodi.com/", className = "STUB_Proxy.ConversionEuroToMAD")
    @ResponseWrapper(localName = "ConversionEuroToMADResponse", targetNamespace = "http://banqueservice.icodi.com/", className = "STUB_Proxy.ConversionEuroToMADResponse")
    @Action(input = "http://banqueservice.icodi.com/BanqueService/ConversionEuroToMADRequest", output = "http://banqueservice.icodi.com/BanqueService/ConversionEuroToMADResponse")
    public double conversionEuroToMAD(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
